name: DevOpsAssignGrp11
description: DevOps Assignment 1 by Group 11

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^2.12.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
